// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	NEXT_CACHE_WORKERS_KV: KVNamespace;
	EMAIL_FROM: "move2comfort_brevo@codestiny.pl";
	EMAIL_FROM_NAME: "Move to comfort";
	EMAIL_REPLY_TO: "move2comfort_brevo@codestiny.pl";
	NEXTJS_ENV: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	DATABASE: D1Database;
	ASSETS: Fetcher;
}
