// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	NEXT_CACHE_WORKERS_KV: KVNamespace;
	EMAIL_FROM: "qzapp@danielbogusz.com";
	EMAIL_FROM_NAME: "Qzapp";
	EMAIL_REPLY_TO: "qzapp@danielbogusz.com";
	CLOUDFLARE_ACCOUNT_ID: string;
	DATABASE_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	NEXT_PUBLIC_TURNSTILE_SITE_KEY: string;
	TURNSTILE_SECRET_KEY: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	RESEND_API_KEY: string;
	BREVO_API_KEY: string;
	DATABASE: D1Database;
	ASSETS: Fetcher;
}
