/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8s080QPh6bu
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@t3-test/components/ui/card"
import { Button } from "@t3-test/components/ui/button"

export function HomePageMock1() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 p-6 bg-primary-500 bg-opacity-50">
      <div className="rounded-xl overflow-hidden relative">
        <img
          alt="Programmer at desk"
          className="absolute inset-0 object-cover w-full h-full"
          height="1080"
          src="/placeholder.svg"
          style={{
            aspectRatio: "1920/1080",
            objectFit: "cover",
          }}
          width="1920"
        />
        <span className="w-full aspect-video rounded-md bg-muted" />
        <div className="py-2 grid gap-2 bg-white bg-opacity-75">
          <h1 className="text-xl font-semibold line-clamp-2">Guided Exercise: Desk Yoga</h1>
          <div className="text-sm">
            <div className="font-semibold">Duration: 15 minutes</div>
            <div className="text-xs text-gray-500 dark:text-gray-400">Instructor: Jane Doe</div>
          </div>
        </div>
      </div>
      <div className="grid sm:grid-cols-2 gap-4 w-full max-w-2xl mx-auto">
        <img
          alt="Movement Instruction 1"
          className="aspect-square object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800"
          height={600}
          src="/placeholder.svg"
          width={600}
        />
        <img
          alt="Movement Instruction 2"
          className="aspect-square object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800"
          height={600}
          src="/placeholder.svg"
          width={600}
        />
        <img
          alt="Movement Instruction 3"
          className="aspect-square object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800"
          height={600}
          src="/placeholder.svg"
          width={600}
        />
        <img
          alt="Movement Instruction 4"
          className="aspect-square object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800"
          height={600}
          src="/placeholder.svg"
          width={600}
        />
      </div>
      <div className="w-full">
        <h2 className="text-2xl font-semibold text-primary-700">Resource Library</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Card className="h-full w-full max-w-2xl">
            <CardHeader>
              <CardTitle>Understanding Ergonomics</CardTitle>
              <CardDescription>
                A comprehensive guide to understanding and implementing ergonomics in your workspace.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Button className="text-primary-700 border-primary-700" variant="outline">
                Read More
              </Button>
            </CardContent>
          </Card>
          <Card className="h-full w-full max-w-2xl">
            <CardHeader>
              <CardTitle>Preventing Carpal Tunnel Syndrome</CardTitle>
              <CardDescription>
                Learn about the causes, symptoms, and prevention strategies for carpal tunnel syndrome.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Button className="text-primary-700 border-primary-700" variant="outline">
                Read More
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
